### ISSUE TITLE
PWM / PID controller rule from template in js syntax

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-js#117]
Hi, i need your help with syntax for PWM and / or PID controller rule creation using JSRule. 

1. My goal is to create such rule (snippset of code after creation in GUI) using JSRule
```
configuration: {}
triggers:
  - id: aa3cd1af-21b2-4ea2-b04b-bdcb4912ad93
    label: PWM Trigger
    configuration:
      deadManSwitch: 50000
      dutycycleItem: HeaterSwitch_dutycycle
      minDutycycle: 0
      interval: 600
      maxDutycycle: 100
    type: pwm.trigger
conditions: []
actions:
  - inputs: {}
    id: "1"
    configuration:
      itemName: HeaterSwitch
    type: core.ItemCommandAction
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript
    type: script.ScriptAction

```
2. My first attemp is: 
rules.JSRule({
  name: "Termostat x PWM rule",
  id:   "Termostat_x_PWM",
  tags: ['Roomx','_DYNAMIC_'],
  overwrite: "true",
  description: "PWM rule for heating actuator",
  triggers: [triggers.pwm('RadiatorACx_homekit_TargetHeatingCoolingMode')],
  execute: data => {
    
  }
of course it is now working as expected. 
Can somebody help me how to define the triggers with items in configuration
