### ISSUE TITLE
Handling ZonedDateTime with js-joda is extremely slow

### ISSUE THREAD

**Issue by dandjo** [openhab/openhab-js#395]
## Expected Behavior

When using ZonedDateTime wrappers via js-joda in ECMAScript (Rules and Scripts), I would expect a similar performance as with all other properties.

## Current Behavior

Looping over a large set of states and using js-joda wrappers within the loop, the loop gets extremely slow. Imagine this example:

```javascript
const logger = log('org.openhab.rule.' + ctx.ruleUID);
// LOCF - last observation carried forward weighting
const midnight = time.toZDT('00:00');
const now = time.toZDT();
const states = items.getItem('some_item').persistence.getAllStatesBetween(midnight, now);
let sum = 0;
let previousTimestamp = midnight;
let previousValue = 0;
for (state of states) {
  const dt = time.Duration.between(previousTimestamp, state.timestamp).toNanos() / 3600000000000;
  sum += previousValue * dt;
  previousTimestamp = state.timestamp;
  previousValue = state.numericState;
}
logger.info(sum + ' (took: ' + time.Duration.between(now, time.toZDT()).toMillis() / 1000 + ' sec)');
```

The output with a state every 5 seconds leads to more than 14 seconds, whereas the following function costs 0.5 seconds.

```javascript
const logger = log('org.openhab.rule.' + ctx.ruleUID);
const midnight = time.toZDT('00:00');
const now = time.toZDT();
const avg = items.getItem('some_item').persistence.averageBetween(midnight, now).numericState;
const hours = time.Duration.between(midnight, now).toNanos() / 3600000000000;
const sum = avg * hours;
logger.info(sum + ' (took: ' + time.Duration.between(now, time.toZDT()).toMillis() / 1000 + ' sec)');
```

## Context

I'm trying to get a "Riemann Sum" implementation of measured power. See discussion here:

[Arithmetic mean vs average linear/step interpolation](https://community.openhab.org/t/arithmetic-mean-vs-average-linear-step-interpolation/159892)

## Your Environment

```
runtimeInfo:
  version: 4.3.0
  buildString: "Build #4362"
locale: en-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.12
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 6.8.0-1013-raspi
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 83704192
  totalMemory: 605028352
  uptime: 29022
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-enigma2
  - binding-http
  - binding-mielecloud
  - binding-modbus
  - binding-mqtt
  - binding-netatmo
  - binding-tado
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-mapdb
  - transformation-jsonpath
  - transformation-regex
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-AT
    languages:
      - en-AT
      - en-GB
      - en-US
      - en
      - de
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: geras
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/130.0.0.0 Safari/537.36
timestamp: 2024-11-04T16:39:30.697Z
```
