### ISSUE TITLE
How to run/execute js rules from ui over long term with restarts and changes

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-js#68]
Currently the js rules produce an identifier based on the rule name and a generated uid.
The uid changes on every rule file save and when openHAB is restarted. (Not sure about the last one tough.)

![image](https://user-images.githubusercontent.com/7161177/148983298-c711d488-98a1-4651-a99f-ef98d08bd78b.png)

Configuration yaml code for the actions:

```yaml
actions:
  - inputs: {}
    id: "4"
    configuration:
      considerConditions: true
      ruleUIDs:
        - Wake-Up-Radio-Automatic-c5b258d4-b32c-43d0-a38d-1f34ab8fa7bd
    type: core.RunRuleAction
    label: Start Wake Up Radio
  - id: "5"
    configuration:
      enable: "false"
      ruleUIDs:
        - arriveAtHome
    type: core.RuleEnablementAction
    label: Disable after first run
```

When i want to run/execute a JS rule from another ui rule, this will only work until the system got restarted or i have changed something.
To get it working again, i have to adapt all rules that are used for running/executing js rules to get the current name with the newly generated uid.

My current workaround would be using virtual items as triggers in the js rules, but this is not very intuitive.
Does someone know a better solution to this?

Probably this is more relevant for openhab-core because it may affect other scripting languages too.
